### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DDDDNNNNNThanh** [samihan-m/smart-fridge-item-tracker#1]
Hello samihan-m. I found your code very helpful and interesting. I have tried your code by Pycharm but unfortunately, there is an error. Can you have me fix it. Thanks a lot!

`Name: Milk Quantity: 0.2 Jugs Expiration Date: None, Name: Cake Quantity: 4.0 slices Expiration Date: None, Name: Cheese Quantity: 8.0 slices Expiration Date: 2021-01-05, Name: Custard Quantity: 16.0 ounces Expiration Date: 2020-12-01, Name: Nacho Cheese Sauce Quantity: 0.75 can Expiration Date: None, Name: Eggs Quantity: 6.0 eggs Expiration Date: 2020-11-09, Name: Hummus Quantity: 24.0 ounces Expiration Date: 2021-02-12, Name: Noodles Quantity: 1.0 box Expiration Date: 2020-11-16, Name: Questionable Pasta Quantity: 1.0 bowl Expiration Date: 2020-11-01
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "kivy\_event.pyx", line 235, in kivy._event.EventDispatcher.__init__
 TypeError: object.__init__() takes exactly one argument (the instance to initialize)
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "C:\Users\Asus\Downloads\smart-fridge-item-tracker-main\smart-fridge-item-tracker-main\FridgeApp.py", line 585, in <module>
     app.run()
   File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\kivy\app.py", line 955, in run
     runTouchApp()
   File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\kivy\base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\kivy\base.py", line 339, in mainloop
     self.idle()
   File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\kivy\base.py", line 383, in idle
     self.dispatch_input()
   File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\kivy\base.py", line 334, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\kivy\base.py", line 263, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\kivy\core\window\__init__.py", line 1664, in on_motion
     self.dispatch('on_touch_up', me)
   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\kivy\core\window\__init__.py", line 1701, in on_touch_up
     if w.dispatch('on_touch_up', touch):
   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\kivy\uix\widget.py", line 611, in on_touch_up
     if child.dispatch('on_touch_up', touch):
   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\kivy\uix\scrollview.py", line 968, in on_touch_up
     if self.dispatch('on_scroll_stop', touch):
   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\kivy\uix\scrollview.py", line 1005, in on_scroll_stop
     self.simulate_touch_down(touch)
   File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\kivy\uix\scrollview.py", line 668, in simulate_touch_down
     ret = super(ScrollView, self).on_touch_down(touch)
   File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\kivy\uix\widget.py", line 589, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\kivy\uix\widget.py", line 589, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\kivy\uix\behaviors\button.py", line 151, in on_touch_down
     self.dispatch('on_press')
   File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
   File "C:\Users\Asus\Downloads\smart-fridge-item-tracker-main\smart-fridge-item-tracker-main\FridgeApp.py", line 160, in item_button_callback
     item_edit_button = Button(text="Edit this Item", id=button.id)
   File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\kivy\uix\behaviors\button.py", line 121, in __init__
     super(ButtonBehavior, self).__init__(**kwargs)
   File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\kivy\uix\label.py", line 317, in __init__
     super(Label, self).__init__(**kwargs)
   File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\kivy\uix\widget.py", line 357, in __init__
     super(Widget, self).__init__(**kwargs)
   File "kivy\_event.pyx", line 238, in kivy._event.EventDispatcher.__init__
 TypeError: Properties ['id'] passed to __init__ may not be existing property names.`

**Comment by DDDDNNNNNThanh** [comment]
I have changed your fridge.kv file according to my computer:
`<Label>:
	#text_size: self.size
	shorten: True
	padding_x: 5
	halign: "center"
	valign: "center"
	font_name: "C:/Users/Asus/Downloads/smart-fridge-item-tracker-main/smart-fridge-item-tracker-main/fonts/Poppins/Poppins-Light"
<Button>:
	text_size: self.size		#this keeps text from going off of the button
	font_size: "20sp"
	font_name: "C:/Users/Asus/Downloads/smart-fridge-item-tracker-main/smart-fridge-item-tracker-main/fonts/Poppins/Poppins-Light.ttf"`

**Comment by samihan-m** [comment]
Hey, I'm glad to have helped you out in some way!
My understanding is that in the time since I last worked on this, the Kivy framework has changed how it works.
For example, the error you ran into with
`TypeError: Properties ['id'] passed to init may not be existing property names.`,
which stemmed from
`item_edit_button = Button(text="Edit this Item", id=button.id)` (you can see this message in the stack trace, too),
is something that is happening because Kivy has removed the ability to provide a value for `id` in the constructor for `Button`.
To get this working again, you will have to remove the `id=button.id` from the `item_edit_button = Button(text="Edit this Item", id=button.id)` line, as well as any other places where we provide an `id` parameter to a Kivy constructor.
I'm not really looking at this code anymore, and I've gotten busy with other projects, so I probably won't update this repository with a fix.
Good luck with your changes! If you have anything you want to ask me, definitely hit me up on Discord at Rudra#8053. I'm pretty available on there.

**Comment by DDDDNNNNNThanh** [comment]
Thank your very much. I will try it right now.
